import { builtinModules } from 'node:module';
import process from 'node:process';
import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// pi-ai's provider-env keeps a `require("node:fs")` for Bun sandboxes. Obsidian Mobile has no
// Node, so that module is swapped for a stub that only reads the explicit overrides.
const providerEnvStub = {
	name: 'pi-ai-provider-env-stub',
	setup(build) {
		build.onResolve({ filter: /[\\/]utils[\\/]provider-env(\.js)?$/ }, (args) => ({
			path: args.path,
			namespace: 'provider-env-stub',
		}));
		build.onLoad({ filter: /.*/, namespace: 'provider-env-stub' }, () => ({
			contents:
				'export function getProviderEnvValue(name, env) { return env?.[name] || undefined; }',
			loader: 'js',
		}));
	},
};

// The MCP SDK loads ajv for its default output validator. The plugin passes its own validator, so
// ajv is swapped for a throwing stub: it keeps ~300 KB and ajv's inert require strings out.
const ajvStub = {
	name: 'ajv-stub',
	setup(build) {
		build.onResolve({ filter: /^ajv(\/.*)?$|^ajv-formats$/ }, (args) => ({
			path: args.path,
			namespace: 'ajv-stub',
		}));
		build.onLoad({ filter: /.*/, namespace: 'ajv-stub' }, () => ({
			contents:
				'function Ajv() { throw new Error("ajv is not bundled"); } export default Ajv; export { Ajv };',
			loader: 'js',
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	platform: 'browser',
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	plugins: [providerEnvStub, ajvStub],
	define: { 'process.env.NODE_ENV': prod ? '"production"' : '"development"' },
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
